master:
  servicePort: 8080
  serviceType: NodePort
  nodePort: 32123
  scriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
  installPlugins:
    - kubernetes:1.6.4
    - workflow-aggregator:2.5
    - workflow-job:2.21
    - credentials-binding:1.16
    - git:3.9.1
agent:
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock

persistence:
  enabled: true
  storageClass: jenkins-volume
  size: 10Gi

networkPolicy:
  enabled: false
  apiVersion: extensions/v1beta1

# Commenting out following because getting this error:
# Error: template: jenkins/templates/deprecation.yaml:277:10: executing
# "jenkins/templates/deprecation.yaml" at <fail "`rbac.install` does no
# longer exist. It has been renamed to `rbac.create` and is enabled by
# default!">: error calling fail: `rbac.install` does no longer exist. It has
# been renamed to `rbac.create` and is enabled by default!
# rbac:
#   install: true
